n = input('Digite algo? ')
print('O tipo primitivo desse valor é', type(n) )
print('Só tem espaços? ', n.isspace())
print('Só tem números? ', n.isnumeric())
print('É alfabético? ', n.isalpha())
print('É alfanumérico? ', n.isalnum())
print('Está tudo em maiúscula? ', n.isupper())
print('Está tudo em minuscúla? ', n.islower())
print('Está capitalizada? ', n.istitle())
